### ISSUE TITLE
doctrine/instantiator version constraint break for 7.0.n builds

### ISSUE THREAD

**Issue by PeeHaa** [sebastianbergmann/phpunit-mock-objects#371] opened 2017-08-01 14:20 UTC
This package should be working on 7.0 (`"php": "^7.0"`), but the `doctrine/instantiator` team bumped the minimum PHP version in a minor release.

Resulting in this package not working anymore on 7.n installs.

>   Problem 1
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.21) does not satisfy that requirement.
  Problem 2
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.21) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects 4.0.2 requires doctrine/instantiator ^1.0.2 -> satisfiable by doctrine/instantiator[1.1.0].
    - Installation request for phpunit/phpunit-mock-objects 4.0.2 -> satisfiable by phpunit/phpunit-mock-objects[4.0.2].

Not sure what the correct course of action is now. Either:

- prevent the install of the latest `doctrine/instantiator`
- bump the minimum PHP version of this package too
- tell the `doctrine/instantiator` maintainers to stop breaking stuff in minors.

**Comment by sebastianbergmann** [comment] 2017-08-01 14:31
Duplicate of #370.

**Closed by sebastianbergmann** 2017-08-01 14:31 UTC
