### ISSUE TITLE
BC break - Trying to configure method "getDefinitions" which cannot be configured

### ISSUE THREAD

**Issue by nicolas-grekas** [sebastianbergmann/phpunit-mock-objects#299] opened 2016-03-23 14:42 UTC
The symfony test suite does not work with https://github.com/sebastianbergmann/phpunit-mock-objects/commit/ec7832ecb77e6d78794e978ffe94e05be6529756

with a phpunit that has been checked out and composer-installed from source
e.g. `phpunit src/Symfony/Component/HttpKernel/` displays:
```
PHPUnit 5.1.7 by Sebastian Bergmann and contributors.
[...]
1) Symfony\Component\HttpKernel\Tests\DependencyInjection\MergeExtensionConfigurationPassTest::testAutoloadMainExtension
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "getDefinitions" which cannot be configured
```

**Comment by sebastianbergmann** [comment] 2016-03-23 14:44
Please provide a minimal, self-contained, reproducing test case.

**Comment by stof** [comment] 2016-03-23 15:13
I think this might be related to the fact that we call ``getMock()`` with just an interface name, without passing a list of methods. Is it now forbidden ?

See https://github.com/symfony/symfony/blob/v2.3.39/src/Symfony/Bridge/Doctrine/Tests/Form/DoctrineOrmTypeGuesserTest.php for such a failing test:

```
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "getClassMetaData" which cannot be configured

/home/travis/build/symfony/symfony/src/Symfony/Bridge/Doctrine/Tests/Form/DoctrineOrmTypeGuesserTest.php:90

/home/travis/build/symfony/symfony/src/Symfony/Bridge/Doctrine/Tests/Form/DoctrineOrmTypeGuesserTest.php:26
```

**Comment by sebastianbergmann** [comment] 2016-03-23 15:28
@stof I do not have time to look at "real world" tests. Please provide a minimal, self-contained, reproducing test case. I need something that I can copy/paste from this issue into a file for running and debugging.

The changes made in ec7832ecb77e6d78794e978ffe94e05be6529756 are not supposed to disallow anything that used to work before. They were made to provide useful error messages when trying to configure methods that cannot be configured (see #296).

**Comment by sebastianbergmann** [comment] 2016-03-23 15:39
As a hotfix, I have tagged https://github.com/sebastianbergmann/phpunit-mock-objects/commit/b90749d8e066e14ffeb9be8d5515d7b0710822f7 as `3.1.1`.

**Comment by nicolas-grekas** [comment] 2016-03-23 16:06
@sebastianbergmann thanks

**Comment by sebastianbergmann** [comment] 2016-03-23 16:12
@stof While I am waiting for a inimal, self-contained, reproducing test case, I have briefly looked at https://github.com/symfony/symfony/blob/v2.3.39/src/Symfony/Bridge/Doctrine/Tests/Form/DoctrineOrmTypeGuesserTest.php.

When I put `var_dump(class_exists('Doctrine\Common\Persistence\ObjectManager'));` just before https://github.com/symfony/symfony/blob/v2.3.39/src/Symfony/Bridge/Doctrine/Tests/Form/DoctrineOrmTypeGuesserTest.php#L89 then I get `false`.

That means that `Doctrine\Common\Persistence\ObjectManager` is not known at this point in time. PHPUnit will therefore create an empty class named `Doctrine\Common\Persistence\ObjectManager` that has no methods.

**Comment by sebastianbergmann** [comment] 2016-03-23 16:19
Just to be clear: the behavior described in https://github.com/sebastianbergmann/phpunit-mock-objects/issues/299#issuecomment-200417047 is expected.

I do not know why the `Doctrine\Common\Persistence\ObjectManager` is not found. The changes made in https://github.com/sebastianbergmann/phpunit-mock-objects/commit/ec7832ecb77e6d78794e978ffe94e05be6529756 make this fact obvious now where the error was silently ignored before.

**Comment by stof** [comment] 2016-03-23 16:26
this looks weird. ``doctrine/orm`` is a dev dependency of Symfony and it itself depends on ``doctrine/common`` (the ORM provides an implementation). So doctrine/common should be available.

**Comment by stof** [comment] 2016-03-23 16:27
actually, I know why you get false: it is an interface, not a class

**Comment by sebastianbergmann** [comment] 2016-03-23 16:44
You're right, of course, and with `interface_exists()` I do get `true`. This problem would be so much easier to analyse if I had a minimal, self-contained, reproducing test case. Any chance of getting one?

**Comment by sebastianbergmann** [comment] 2016-03-23 16:57
I think I have found the root cause: the simple/naive `in_array()` call in https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Builder/InvocationMocker.php#L271 is not sufficient.

In the case of https://github.com/symfony/symfony/blob/v2.3.39/src/Symfony/Bridge/Doctrine/Tests/Form/DoctrineOrmTypeGuesserTest.php, `$constraint` is `'getClassMetaData'` whereas `$this->configurableMethods` contains `'getClassMetadata'`.

Yay! for PHP's case insensitivity.

**Comment by sebastianbergmann** [comment] 2016-03-23 17:01
After https://github.com/sebastianbergmann/phpunit-mock-objects/commit/75d58e369fd14e2fab911e44e45bf6fde6e85f2a the tests in https://github.com/symfony/symfony/blob/v2.3.39/src/Symfony/Bridge/Doctrine/Tests/Form/DoctrineOrmTypeGuesserTest.php work for me.

**Comment by sebastianbergmann** [comment] 2016-03-23 17:03
I now get the following errors:
```
There were 12 errors:

1) Symfony\Component\Form\Tests\Extension\Validator\Constraints\FormValidatorTest::testNoViolationIfAllowExtraData
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "addViolationAt" which cannot be configured

/home/sb/symfony/src/Symfony/Component/Form/Tests/Extension/Validator/Constraints/FormValidatorTest.php:627

2) Symfony\Component\Form\Tests\Extension\Validator\ValidatorExtensionTest::test2Dot5ValidationApi
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "getMetadataFactory" which cannot be configured

/home/sb/symfony/src/Symfony/Component/Form/Tests/Extension/Validator/ValidatorExtensionTest.php:43

3) Symfony\Component\HttpKernel\Tests\DependencyInjection\MergeExtensionConfigurationPassTest::testAutoloadMainExtension
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "getDefinitions" which cannot be configured

/home/sb/symfony/src/Symfony/Component/HttpKernel/Tests/DependencyInjection/MergeExtensionConfigurationPassTest.php:45

4) Symfony\Component\HttpKernel\Tests\EventListener\RouterListenerTest::testSubRequestWithDifferentMethod
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "getContext" which cannot be configured

/home/sb/symfony/src/Symfony/Component/HttpKernel/Tests/EventListener/RouterListenerTest.php:115

5) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testTerminateDelegatesTerminationOnlyForTerminableInterface
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "terminate" which cannot be configured

/home/sb/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTest.php:35

6) Symfony\Component\HttpKernel\Tests\KernelTest::testClassCacheIsNotLoadedByDefault
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "doLoadClassCache" which cannot be configured

/home/sb/symfony/src/Symfony/Component/HttpKernel/Tests/KernelTest.php:103

7) Symfony\Component\HttpKernel\Tests\KernelTest::testTerminateDelegatesTerminationOnlyForTerminableInterface
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "terminate" which cannot be configured

/home/sb/symfony/src/Symfony/Component/HttpKernel/Tests/KernelTest.php:696

8) Symfony\Component\Translation\Tests\Writer\TranslationWriterTest::testDisableBackup
PHPUnit_Framework_MockObject_RuntimeException: Trying to configure method "setBackup" which cannot be configured

/home/sb/symfony/src/Symfony/Component/Translation/Tests/Writer/TranslationWriterTest.php:36

9) Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest::testRenderViewTwig
Error: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\Controller::renderView() from context 'Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest'

/home/sb/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTest.php:256

10) Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest::testRenderTwig
Error: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\Controller::render() from context 'Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest'

/home/sb/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTest.php:272

11) Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest::testStreamTwig
Error: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\Controller::stream() from context 'Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest'

/home/sb/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTest.php:287

12) Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest::testCreateAccessDeniedException
Error: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\Controller::createAccessDeniedException() from context 'Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest'

/home/sb/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTest.php:328
```
As there are still `Trying to configure method "..." which cannot be configured` errors I do not think that all BC breaks introduced in https://github.com/sebastianbergmann/phpunit-mock-objects/commit/ec7832ecb77e6d78794e978ffe94e05be6529756 are solved yet.

**Comment by sebastianbergmann** [comment] 2016-03-23 17:12
I stopped debugging after looking at the first remaining error because `ExecutionContextInterface` does not have a method named `addViolationAt`. This is an error that was silently ignored before.

**Comment by stof** [comment] 2016-03-23 17:21
For Symfony\Component\Templating\Tests\DelegatingEngineTest::testStreamRequiresStreamingEngine, the issue is a bug in the Symfony testsuite. We are indeed trying to configure a non-existent method.

I think it may be great to have a different error message when the method does not exist at all rather than existing but not configurable (final or private). It would make it easier to understand the mistake.

**Comment by sebastianbergmann** [comment] 2016-03-23 17:40
I agree but I am afraid that this would require significant work. I will probably do it eventually (unless someone beats me to it with a pull request) but no promises as to when.

**Comment by stof** [comment] 2016-03-23 17:47
@sebastianbergmann a first easy step might be to add more explanations in the exception message about what ``cannot be configured`` means for PHPUnit (as people using PHPUnit might not know the rules determining this)

**Comment by sebastianbergmann** [comment] 2016-03-23 17:51
Attempted in https://github.com/sebastianbergmann/phpunit-mock-objects/commit/957b4b2c47a172778d2f9d1c99e3cee25095c548

**Comment by sebastianbergmann** [comment] 2016-03-23 21:45
@stof @nicolas-grekas Is the current state of `master` ready to be released as `3.1.2`?

**Comment by nicolas-grekas** [comment] 2016-03-23 22:20
OK for me, we'll fix Symfony's tests to not mock undefined methods afterwards. Thanks

**Comment by sebastianbergmann** [comment] 2016-03-24 05:55
Thank you for bringing this to my attention, @nicolas-grekas and @stof, and for helping to resolve it.

**Closed by sebastianbergmann** 2016-03-24 05:55 UTC
Labels: bug

**Comment by sebastianbergmann** [comment] 2016-03-24 06:13
Sidenote: with PHPUnit 5.3, due on April 1, these errors will be warnings:
```
There were 4 errors:

1) Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest::testRenderViewTwig
Error: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\Controller::renderView() from context 'Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest'

/home/sb/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTest.php:256

2) Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest::testRenderTwig
Error: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\Controller::render() from context 'Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest'

/home/sb/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTest.php:272

3) Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest::testStreamTwig
Error: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\Controller::stream() from context 'Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest'

/home/sb/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTest.php:287

4) Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest::testCreateAccessDeniedException
Error: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\Controller::createAccessDeniedException() from context 'Symfony\Bundle\FrameworkBundle\Tests\Controller\ControllerTest'

/home/sb/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTest.php:328

--

There were 8 warnings:

1) Symfony\Component\Form\Tests\Extension\Validator\Constraints\FormValidatorTest::testNoViolationIfAllowExtraData
Trying to configure method "addViolationAt" which cannot be configured because it does not exist, has not been specified, is final, or is static

2) Symfony\Component\Form\Tests\Extension\Validator\ValidatorExtensionTest::test2Dot5ValidationApi
Trying to configure method "getMetadataFactory" which cannot be configured because it does not exist, has not been specified, is final, or is static

3) Symfony\Component\HttpKernel\Tests\DependencyInjection\MergeExtensionConfigurationPassTest::testAutoloadMainExtension
Trying to configure method "getDefinitions" which cannot be configured because it does not exist, has not been specified, is final, or is static

4) Symfony\Component\HttpKernel\Tests\EventListener\RouterListenerTest::testSubRequestWithDifferentMethod
Trying to configure method "getContext" which cannot be configured because it does not exist, has not been specified, is final, or is static

5) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testTerminateDelegatesTerminationOnlyForTerminableInterface
Trying to configure method "terminate" which cannot be configured because it does not exist, has not been specified, is final, or is static

6) Symfony\Component\HttpKernel\Tests\KernelTest::testClassCacheIsNotLoadedByDefault
Trying to configure method "doLoadClassCache" which cannot be configured because it does not exist, has not been specified, is final, or is static

7) Symfony\Component\HttpKernel\Tests\KernelTest::testTerminateDelegatesTerminationOnlyForTerminableInterface
Trying to configure method "terminate" which cannot be configured because it does not exist, has not been specified, is final, or is static

8) Symfony\Component\Translation\Tests\Writer\TranslationWriterTest::testDisableBackup
Trying to configure method "setBackup" which cannot be configured because it does not exist, has not been specified, is final, or is static
```
